### ISSUE TITLE
Feature request: "Hybrid" Warehouses?

### ISSUE THREAD

**Issue by Flow86** [Anoyomouse/Warehousing#2]
Hi,

is it possible to get some "hybrid warehouses", like "requester+storage" and "requester+passive"?

like the one from https://github.com/Phenix0cs/Smarter-chests but not only the requester+storage combination?

Thank you!

**Comment by Anoyomouse** [comment]
Hey

Looking at this mod and how it works, i wouldn't want to pull their mod into mine, i'd far rather suggest them pulling in a warehouse from their side and manage it with their scripts.

I'd be happy for them to make a warehouse version of their chest .. but i'm also worried that it will cause a whole lot of lag because you're working on duplicating 2000 item slots between 2 entities on the same spot, so you're doubling all warehouse access ... maybe not such a good idea

**Comment by dgw** [comment]
Just to note, Factorio 0.16 added a buffer chest type that combines requester and passive provider. Would that be sufficient? I'm tracking implementation of that warehouse/storehouse type in #22.

**Comment by dgw** [comment]
This is unlikely to ever happen, especially because buffer warehouses (based on the buffer chests added in Factorio 0.16) will soon exist. Going to close this feature request.
